name: Validate IaC - Terraform

on:
  push:
    branches: [ main ]
    paths:
      - 'Iac/Terraform/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Iac/Terraform/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-v1:
    name: 'Validate Terraform - v1'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Validate
      run: |
        terraform init
        terraform validate
      working-directory: IaC/Terraform/v1

  terraform-v2:
    name: 'Validate Terraform - v2'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Validate
      run: |
        terraform init
        terraform validate
      working-directory: IaC/Terraform/v2

