name: Validate IaC - Azure Bicep

on:
  push:
    branches: [ main ]
    paths:
      - 'IaC/Bicep/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'IaC/Bicep/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bicep-v1:
    name: 'Validate Bicep - v1'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Bicep
      uses: anthony-c-martin/setup-bicep@v0.1

    - name: Bicep Lint
      run: |
        bicep lint deploy.bicep
      working-directory: IaC/Bicep/v1

    - name: Bicep Build
      run: |
        bicep build deploy.bicep
      working-directory: IaC/Bicep/v1

  bicep-v2:
    name: 'Validate Bicep - v2'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Bicep
      uses: anthony-c-martin/setup-bicep@v0.1

    - name: Bicep Lint
      run: |
        bicep lint deploy.bicep
      working-directory: IaC/Bicep/v2

    - name: Bicep Build
      run: |
        bicep build deploy.bicep
      working-directory: IaC/Bicep/v2

